site_name: QD Garden
site_url: https://aldridgexia.github.io/qdgarden
repo_url: https://github.com/Aldridgexia/qdgarden
repo_name: Aldridgexia/qdgarden
nav:
  - Home: index.md
  - CS:
    - Database: cs/database.md
    - Sorting: cs/sorting.md
    - Python: cs/python.md
  - Math:
    - Linear Algebra: math/linear_algebra.md
    - Probability: math/probability.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences