site_name: QD Garden
site_url: https://aldridgexia.github.io/qdgarden
repo_url: https://github.com/Aldridgexia/qdgarden
repo_name: Aldridgexia/qdgarden
nav:
  - Home: index.md
  - CS:
    - Database: cs/database.md
    - Sorting: cs/sorting.md
    - Python: cs/python.md
  - Math:
    - Linear Algebra: math/linear_algebra.md
    - Probability: math/probability.md
  - Resources: resources.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - content.code.copy
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js