site_name: QD Garden
site_url: https://aldridgexia.github.io/qdgarden/
nav:
  - Home: index.md
  - CS:
    - Database: database.md
theme:
  name: material
  features:
    - navigation.instant
plugins:
  - search
  - tags
